### ISSUE TITLE
default/standard setting; top overlays in combination with bottom ratings are result in cutting

### ISSUE THREAD

**Issue by michpas** [ilarramendi/Cover-Ratings#44] opened 2021-05-16 13:46 UTC
see image from plex/jelly fin with the standard settings
https://ibb.co/GWw7C4W

I understand the too many 'ratings'on the left bar, but in some cases the top blue ray bar is half cut and on bottom PG13 is cut: example dunkirk
The hamilton covers shows another variance. PG13 is a bit more readable, but on top side the 'good movies' banner is cut more.

The gentlemen is fine; also the bottom rating, i guess as it doesn't have the 'top-cover blueray/good movies'.

**Comment by ilarramendi** [comment] 2021-05-16 19:47
Thats weird, they are generating ok on my system, did you delete the whole wd and tried again? Ill take a look at this anyway

**Comment by ilarramendi** [comment] 2021-05-16 22:10
Im not able to reproduce, my images look like this with a fresh work directory an docker container:


![folder](https://user-images.githubusercontent.com/30437204/118414350-5992f280-b67a-11eb-8d6d-3215f6af63c6.png)

**Comment by michpas** [comment] 2021-05-17 18:16
Hi. I tested the new version. 

Indeed, Found that indeed the image itself is correct; when you open it from file folder.
but when it's displayed in jellyfin/plex it cuts.
Example image on the players vs image on windows.

https://ibb.co/DRmCs6b

**Comment by ilarramendi** [comment] 2021-05-17 23:12
Yes, images with Bluray or Good Movies cover have different height, thats weird, this isnt a problem in emby!
![2021-05-17 20_12_24-Movies](https://user-images.githubusercontent.com/30437204/118567456-36d10e80-b74c-11eb-8003-90aa7ff29400.png)

**Comment by michpas** [comment] 2021-05-18 05:14
Can you see how your covers look on.plex or jellyfin? In both, my covers are 'cut'.
Need to find out if this is relsted to plex/jellyfin or related to my movies.

**Comment by michpas** [comment] 2021-05-18 05:47
![image](https://user-images.githubusercontent.com/66222810/118597636-3c127580-b7ad-11eb-8315-e118cfead460.png)

**Comment by ilarramendi** [comment] 2021-05-18 15:18
Looks like its a problem with plex/jf ill test this out later.
If they dont support different aspect ratio for images ill probably resize these covers to work.
PD: Did the "kids" overly fom v0.8 look ok? Since these images also had different height!

**Comment by michpas** [comment] 2021-05-18 17:44
hi. On the kidsoverlay. I can't remember if they looked ok. I also experimented a lot with different settings and landed on the below:
![image](https://user-images.githubusercontent.com/66222810/118698673-fd160b80-b810-11eb-834d-6a2ef0ab9308.png)
which was simply using the mediatype routine and showing SD, HD; with these images being the text in yellow.
I also wanted to experiment with whole covers as an overlay image, like you developed, but couldn't easily find how to config.

**Comment by michpas** [comment] 2021-05-18 18:02
for the whole 'covers', maybe its an idea to overlay with a full image that people can easily modify.
![image](https://user-images.githubusercontent.com/66222810/118700988-829abb00-b813-11eb-93a5-b5c8a38ce563.png)
In the current version I can only find the 'logo' image. Pretty impressive how I guess you used style sheets to 'build' the cover.

**Comment by ilarramendi** [comment] 2021-05-27 00:54
Should be fixed now, sorry for the delay!

**Closed by ilarramendi** 2021-05-27 00:54 UTC
